ARG DOCKER_REGISTRY=ghcr.io
ARG VERSION={{.KagentVersion}}
FROM $DOCKER_REGISTRY/kagent-dev/kagent/kagent-adk:$VERSION

WORKDIR /app

COPY .python-version .python-version
COPY pyproject.toml pyproject.toml
COPY README.md README.md
COPY {{.Name}}/ {{.Name}}/

RUN uv sync

CMD ["{{.Name}}"]
