ARG DOCKER_REGISTRY=ghcr.io
ARG VERSION={{.KagentVersion}}
FROM $DOCKER_REGISTRY/kagent-dev/kagent/kagent-crewai:$VERSION

WORKDIR /app

COPY  {{.Name}}/ {{.Name}}/
COPY  pyproject.toml pyproject.toml
COPY  README.md README.md

RUN uv sync

CMD ["{{.Name}}"]
